"""add_discord_webhook_url_to_programs

Revision ID: 871ec763de7d
Revises: a0c3550f5556
Create Date: 2025-11-30 19:34:59.151500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871ec763de7d'
down_revision = 'a0c3550f5556'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('discord_webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'discord_webhook_url')
    # ### end Alembic commands ###
