"""add_scan_frequency

Revision ID: e1f72bb2977b
Revises: 871ec763de7d
Create Date: 2025-11-30 20:25:52.358016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f72bb2977b'
down_revision = '871ec763de7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('scan_frequency', sa.Enum('never', 'daily', 'weekly', 'monthly', name='scanfrequency'), nullable=False, server_default='never'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'scan_frequency')
    # ### end Alembic commands ###
