"""Add performance indexes for EASM platform

Revision ID: f5a6b7c8d9e0
Revises: e4f5a6b7c8d9
Create Date: 2025-02-03 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f5a6b7c8d9e0'
down_revision = 'e4f5a6b7c8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Assets table indexes
    op.create_index('idx_assets_scope_value', 'assets', ['scope_id', 'value'], unique=False)
    op.create_index('idx_assets_last_scanned', 'assets', ['last_scanned_at'], unique=False)
    op.create_index('idx_assets_criticality', 'assets', ['criticality'], unique=False)
    
    # Vulnerabilities table indexes
    op.create_index('idx_vulnerabilities_severity_status', 'vulnerabilities', ['severity', 'status'], unique=False)
    op.create_index('idx_vulnerabilities_created_at', 'vulnerabilities', ['created_at'], unique=False)
    
    # Scans table indexes
    op.create_index('idx_scans_status', 'scans', ['status'], unique=False)
    op.create_index('idx_scans_started_at', 'scans', ['started_at'], unique=False)
    op.create_index('idx_scans_scope_profile', 'scans', ['scope_id', 'scan_profile'], unique=False)
    
    # Services table indexes
    op.create_index('idx_services_port', 'services', ['port'], unique=False)
    op.create_index('idx_services_technologies', 'services', ['technologies'], unique=False, postgresql_using='gin')
    
    # Scan events table indexes
    op.create_index('idx_scan_events_scan_id', 'scan_events', ['scan_id'], unique=False)
    op.create_index('idx_scan_events_created_at', 'scan_events', ['created_at'], unique=False)
    
    # System logs table indexes
    op.create_index('idx_system_logs_level', 'system_logs', ['level'], unique=False)
    op.create_index('idx_system_logs_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_system_logs_user_id', 'system_logs', ['user_id'], unique=False)
    
    # Passive intel indexes
    op.create_index('idx_dns_records_asset_id', 'dns_records', ['asset_id'], unique=False)
    op.create_index('idx_certificates_asset_id', 'certificates', ['asset_id'], unique=False)
    op.create_index('idx_historical_urls_asset_id', 'historical_urls', ['asset_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop assets indexes
    op.drop_index('idx_assets_scope_value', table_name='assets')
    op.drop_index('idx_assets_last_scanned', table_name='assets')
    op.drop_index('idx_assets_criticality', table_name='assets')
    
    # Drop vulnerabilities indexes
    op.drop_index('idx_vulnerabilities_severity_status', table_name='vulnerabilities')
    op.drop_index('idx_vulnerabilities_created_at', table_name='vulnerabilities')
    
    # Drop scans indexes
    op.drop_index('idx_scans_status', table_name='scans')
    op.drop_index('idx_scans_started_at', table_name='scans')
    op.drop_index('idx_scans_scope_profile', table_name='scans')
    
    # Drop services indexes
    op.drop_index('idx_services_port', table_name='services')
    op.drop_index('idx_services_technologies', table_name='services', postgresql_using='gin')
    
    # Drop scan events indexes
    op.drop_index('idx_scan_events_scan_id', table_name='scan_events')
    op.drop_index('idx_scan_events_created_at', table_name='scan_events')
    
    # Drop system logs indexes
    op.drop_index('idx_system_logs_level', table_name='system_logs')
    op.drop_index('idx_system_logs_created_at', table_name='system_logs')
    op.drop_index('idx_system_logs_user_id', table_name='system_logs')
    
    # Drop passive intel indexes
    op.drop_index('idx_dns_records_asset_id', table_name='dns_records')
    op.drop_index('idx_certificates_asset_id', table_name='certificates')
    op.drop_index('idx_historical_urls_asset_id', table_name='historical_urls')
    
    # ### end Alembic commands ###
